# prefix を Ctrl-Space に変更
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# vim風ペイン移動
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# マウス有効（最初は便利）
set -g mouse on

# 設定再読み込み
bind r source-file ~/.tmux.conf \; display "tmux.conf reloaded"

